config/routes.rb
Rails.application.routes.draw do
  root 'movies#index'
  devise_for :users
  resources :movies do
    resources :reviews
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :reviews

  def self.search(search)
    keyword = search.downcase
    where("lower(title) LIKE ?", "%#{keyword}%")
  end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    if params[:search]
      @movies = Movie.search(params[:search])
      render '_search'
    else
      @movies = Movie.all
      today = Date.today 
      @this_week_movies = Movie.where(week_released: today.at_beginning_of_week..today.at_end_of_week)
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :description, :year_released, :genre, :content_rating, :rating_id)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_movie
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)
    @review.movie = @movie
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to @movie, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:rating, :comment, :user_id)
    end

    def set_movie
      @movie = Movie.find(params[:movie_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  def movie_rating(movie)
<<<<<<< HEAD
    movie.reviews.blank? ? '?' : movie.reviews.average(:rating).floor
=======
    movie.reviews.blank? ? '?' : movie.reviews.average(:rating).floor #movie.reviews.sum(&:rating) / movie.reviews.count
>>>>>>> 6c9acc580e13ea877dfbff51dba3100a6ebdd25e
  end

  def colorize_movie_rating(rating)
    if rating >= 60
      "green_rating"
    elsif rating >= 30
      "orange_rating"
    elsif rating >= 0
      "red_rating"
    else
      "no_rating"
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RottenPotatoes</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <section class="header_movies">
        <a href="<%= movies_path %>" class="d-flex">
          <div class="header_logo p-2 align-self-center">
            <%= image_tag asset_path('potato.png'), height: 60 %>
          </div>
          <div class="header_title p-2 align-self-center">
            <h1>Rotten Potatoes</h1>
          </div>
        </a>
      </section>
      
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :movie_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :movie_description %>
  </div>

  <div class="field">
    <%= form.label :year_released %>
    <%= form.number_field :year_released, id: :movie_year_released %>
  </div>

  <div class="field">
    <%= form.label :genre %>
    <%= form.text_field :genre, id: :movie_genre %>
  </div>

  <div class="field">
    <%= form.label :content_rating %>
    <%= form.text_field :content_rating, id: :movie_content_rating %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<a href="<%= movie_path(movie) %>">
  <div class="movies_item d-flex justify-content-between">
    <div class="movie_info p-2 d-flex">
      <div class="movie_image p-2 align-self-start">
        <div class="movie_poster"></div>
      </div>
      <div class="movie_details p-2 align-self-start">
        <div class="movie_title">
          <h3><%= movie.title %></h3>
        </div>
        <div class="movie_content_rating">
          <p><%= movie.content_rating %></p>
        </div>
        <div class="movie_review_count">
          <p><%= pluralize(movie.reviews.count, 'Review') %></p>
        </div>
      </div>
    </div>
    <div class="movie_rating p-2 align-self-center">
      <div class="movie_score <%= colorize_movie_rating(movie_rating movie) %>">
        <h3><%= movie_rating movie %></h3>
      </div>
    </div>
  </div>
</a>

app/views/movies/_search.html.erb
<section class="movies">
  <div class="movies_section_title">
    <h2><%= pluralize @movies.size, 'Search Result' %></h2>
  </div>
  <div class="movies_list">
    <%= render @movies %>
  </div>
</section>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<section class="search">
  <div class="search_bar">
    <%= form_tag(@movie, method: "get", class: 'd-flex justify-content-center') do %>
      <%= text_field_tag :search, params[:search], placeholder: "Search movie", class: 'p-2 align-self-center' %>
      <%= submit_tag "Search", class: 'p-2 align-self-center' %>
    <% end %>
  </div>
</section>

<section class="movies">
  <div class="movies_section_title">
    <h2>This Week</h2>
  </div>
  <div class="movies_list">
    <%= render @this_week_movies %>
  </div>
</section>

<section class="movies">
  <div class="movies_section_title">
    <h2>All Time</h2>
  </div>
  <div class="movies_list">
    <%= render @movies %>
  </div>
</section>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<section class="movie">
  <div class="movie_title d-flex justify-content-center align-items-end">
    <h2 class="p-2 align-items-center"><%= @movie.title %></h2>
    <span class="p-2"><%= @movie.year_released %></span>
  </div>

  <div class="movie_poster">
    <div class="movie_poster_image">

    </div>
  </div>

  <div class="movie_info d-flex justify-content-between">
    <div class="movie_content p-2">
      <p><%= @movie.content_rating %> | <%= @movie.genre %></p>
    </div>
    <div class="movie_avg_potato_score p-2 d-flex">
      <div class="potato_review p-2">
        <div class="potato_review_label">
          <h2>Avg Potato Score</h2>
        </div>
        <div class="potato_review_count">
          <p>out of <%= pluralize(@movie.reviews.count, 'Review') %></p>
        </div>
      </div>
      <div class="potato_review_score p-2 <%= colorize_movie_rating(movie_rating @movie) %>">
        <h3><%= movie_rating @movie %></h3>
      </div>
    </div>
  </div>

  <div class="movie_description">
    <p><%= @movie.description %></p>
  </div>

  <div class="reviews_nav d-flex justify-content-center">
    <% if user_signed_in? %>
      <%= link_to 'Write a Review', new_movie_review_url(@movie), class: 'btn btn-primary p-2' %> 
    <% else %>
      <%= link_to 'Sign in to Review this movie', new_user_session_url, class: 'btn btn-primary p-2' %>
    <% end %>
  </div>
</section>

<section class="reviews">
  <div class="reviews_header">
    <h2>Reviews</h2>
  </div>
  
  <div class="reviews_list">
    <% @movie.reviews.each do |review| %>
    <div class="review_item d-flex justify-content-between">
      <div class="review_info p-2 align-self-start">
        <div class="review_user">
          <p><%= review.user.username %><p>
        </div>  
        <div class="review_comment">
          <p><%= review.comment %></p>
        </div>
      </div>
      <div class="review_rating p-2 align-self-start <%= colorize_movie_rating(review.rating) %>">
        <h3><%= review.rating %></h3>
      </div>
    </div>
    <% end %>
  </div>
</section>

app/views/reviews/_form.html.erb
<section class="review_form">
  <%= form_with(model: [@movie, review], local: true) do |form| %>
    <% if review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% review.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="textarea">
      <div class="field">
        <%= form.text_area :comment, id: :review_comment, placeholder: 'What did you think about this movie?', onclick: 'event.preventDefault();' %>
      </div>

    <div class="field">
      <%= form.number_field :rating, id: :review_rating, placeholder: 'Rating' %>
    </div>

    <div class="actions">
      <%= form.submit 'Submit Review' %><br>
      <%= link_to 'Back', movies_path, class: 'btn' %>
    </div>
  <% end %>
</section>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Comment</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.rating %></td>
        <td><%= review.comment %></td>
        <td><%= review.user %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<section class="reviews">
  <div class="reviews_header">
    <h2>Write a Review</h2>
  </div>
</section>

<%= render 'form', review: @review %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @review.comment %>
</p>

<p>
  <strong>User:</strong>
  <%= @review.user %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>